### ISSUE TITLE
Gestion de sessions entre bornes

### ISSUE THREAD

**Issue by mohierf** [IPM-France/glpi_plugin_kiosks#76]
Mise en place d'une API REST utilisable par les bornes pour gérer des sessions.

Cette API permet d'ouvrir et de partage une session sécurisée entre deux bornes, ou une borne et un PC. 

 L'ouverture de la session est à l'initiative d'une des parties. Les autres parties se connectent à la session en fournissant l'identifiant de session qui a été donné par le backend à l'ouverture de la session.

 Lorsqu'une session existe, toutes les parties peuvent GET, POST, PATCH, DELETE des données et/ou des fichiers qui seront mémorisés.

**Comment by ddurieux** [comment]
Backend en Eve
+ nom de session
+ log de tous les events
+ gestion des documents

**Comment by mohierf** [comment]
Après discussion interne, le mode de fonctionnement retenu est le suivant: 
- celui qui ouvre une session fournit un identifiant de réunion (*meetingId*)
- le backend créé une session (*sessionId*) associée au *meetingId* et la marque comme ouverte (*opened*)
- les autres participants de la session pourront se connecter dans une session ouverte avec un identifiant de réunion
- un participant peut se déconnecter et se reconnecter dans une session ouverte
- lorsque tous les participants sont déconnectés, le backend marque la session comme fermée

**Comment by mohierf** [comment]
@bouchenh, @lbarsali : ça me parait clair par rapport à notre discussion ...

**Comment by mohierf** [comment]
Créer une session:
 - POST sur userservice_session

Joindre une session:
 - POST sur userservice_session_user

Rester dans une session:
 - POST event pour la session (=> mise à jour last_ping)
 - UPDATE sur userservice_session_user (=> mise à jour last_ping)

Quitter la session:
 - POST event quit pour la session
 - UPDATE sur userservice_session_user (last_ping à 0)
 - timeout 1mn sans activité du user
